# Generated by Django 4.0.6 on 2024-01-16 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiceApp', '0004_bet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bet',
        ),
    ]
