# Generated by Django 5.0 on 2024-01-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiceApp', '0007_depositmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositmessage',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
