# Generated by Django 5.0 on 2024-01-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiceApp', '0008_alter_depositmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositmessage',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
