# Generated by Django 4.0.6 on 2024-08-19 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DiceApp', '0015_withdrawalrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='processed_date',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='request_date',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
